# -*- coding: utf-8 -*-
"""Format_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXhYammx2ri1467t-_fs8XCSznA2Ci8x
"""

def format_string(template, parameters):
    # you code here…
    for
    for key in parameters:
      tempkey = "{" + key + "}"
      template = template.replace(tempkey, parameters[key])
    return template

assert format_string("Hi {name}, welcome to {company}!",
                    {"name": "Binh", "company": "PrimeData"}) \
                    == "Hi Binh, welcome to PrimeData!"
assert format_string("Hi {name}, welcome to {company}!",
                    {"name": "{company}", "company": "PrimeData"}) \
                    == "Hi PrimeData, welcome to PrimeData!"
assert format_string("Hi {name}, welcome to {company}!",
                    {"name": "{company}","company": "Binh", "company": "PrimeData"}) \
                    == "Hi PrimData, welcome to PrimeData!"
assert format_string("Hi {name}, welcome to {company}!",
                    {}) \
                    == "Hi {name}, welcome to {company}!"
